server:
  port: 8002
spring:
  application:
    name: xunzhi-agent-admin
  profiles:
    include: satoken
  servlet:
    multipart:
      location: src/main/resources/temp/upload
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: xunzhi_agent
      # 如果需要认证，可以配置用户名和密码
      # username: your_username
      # password: your_password
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
      timeout: 10000ms
  # Spring配置
  # 定时任务配置
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: redis-session-task-
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        thread-name-prefix: redis-session-async-
xunfei:
  lat-key:
    app-id: 96f3a359
    api-key: e8565c438f59b301616e0498a86ad95d
    api-secret: OGZkZGQ5ZDY0Yzc4MTllZWI3ZmU2MDU4

# 豆包大模型配置
doubao:
  api-key: 59378d07-9d8b-41fc-9e48-05fb806c2ac9
  secret-key: WkdWa1ltUTJZMlZsWTJFNU5ETXhZbUl3TXpCaVltTTVaamM1TWpWbVltSQ==
  region: cn-beijing  # 地域，固定为 cn-beijing
  model-id: doubao-lite-32k-character-250228  # 模型名称（含版本）
  base-url: https://ark.cn-beijing.volces.com/api/v3  # API 端点
  timeout: 1800  # 超时时间（秒）
  connect-timeout: 20  # 连接超时（秒）
  retry-times: 2  # 重试次数

# 火山引擎配置（基于官方示例）
volcengine:
  api-key: 6690375602  # 对应官方示例中的APP_ID
  access-key: M2S3xBuHbaQn1wHsSzvjzBZuiLZGngTt  # 对应官方示例中的ACCESS_TOKEN
  region: volcano_icl  # 默认区域
  tts:
    default-voice: BV001  # 基于官方示例
    default-format: mp3
    default-speed: 1.0
    default-pitch: 1.0
    default-volume: 1.0
    default-emotion: happy
  voice-training:
    base-url: https://openspeech.bytedance.com/api/v1/voice_training
    min-audio-files: 10
    max-audio-files: 100
    max-file-size: 10485760  # 10MB
    supported-formats: ["wav", "mp3"]
    supported-training-types: ["standard", "premium"]
    supported-languages: ["zh-CN", "en-US"]
    default-training-duration: 30

# Coze工作流配置
coze:
  api-key: pat_PXqpYfiJrmCVYTH3fvGHvvl6nACH0FVW8DLA2rxE94YPaBaEIansXogq3IHqaZY5  # Coze API密钥
  base-url: https://api.coze.cn  # API基础URL
  timeout: 30000  # 超时时间（毫秒）
  connect-timeout: 10000  # 连接超时时间（毫秒）
  read-timeout: 30000  # 读取超时时间（毫秒）
  retry-times: 2  # 重试次数
  workflow:
    default-workflow-id: ${COZE_DEFAULT_WORKFLOW_ID:test-workflow-id}  # 默认工作流ID
    enable-async: true  # 是否启用异步执行
    max-concurrency: 10  # 最大并发数

xunzhi-agent:
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  redis-session:
      # 是否启用Redis会话缓存
    enable: true
      # 会话消息缓存过期时间（秒），默认7天
    message-expire-seconds: 604800
      # 异步同步到数据库的延迟时间（秒），默认30秒
    sync-delay-seconds: 30
      # 批量同步的最大消息数量
    batch-sync-size: 100
      # 同步队列的最大长度
    max-queue-size: 10000
      # 清理任务的执行间隔（秒），默认5分钟
    clean-interval-seconds: 300
