server:
  port: 8002
spring:
  application:
    name: xunzhi-agent-admin
  profiles:
    include: satoken
  servlet:
    multipart:
      location: src/main/resources/temp/upload
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: xunzhi_agent
      # 如果需要认证，可以配置用户名和密码
      # username: your_username
      # password: your_password
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
      timeout: 10000ms
  # Spring配置
  # 定时任务配置
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: redis-session-task-
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
        thread-name-prefix: redis-session-async-
xunfei:
  lat-key:
    app-id: 96f3a359
    api-key: e8565c438f59b301616e0498a86ad95d
    api-secret: OGZkZGQ5ZDY0Yzc4MTllZWI3ZmU2MDU4

xunzhi-agent:
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
  redis-session:
      # 是否启用Redis会话缓存
    enable: true
      # 会话消息缓存过期时间（秒），默认7天
    message-expire-seconds: 604800
      # 异步同步到数据库的延迟时间（秒），默认30秒
    sync-delay-seconds: 30
      # 批量同步的最大消息数量
    batch-sync-size: 100
      # 同步队列的最大长度
    max-queue-size: 10000
      # 清理任务的执行间隔（秒），默认5分钟
    clean-interval-seconds: 300
